### ISSUE TITLE
Allow support in LDA, BayesianLDA, SubspaceLDA, and BayesianSubspaceLDA for unique target class in training.  

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJMultivariateStatsInterface.jl#41]
There is currently a check that catches if training data only presents one class (even if pool contains more). This is causing issues in subsampling for small data sets. I've checked, and the core model does not have an issue with setting `nc=1`. So this should be fixable. But this issue will first require:

- [x] #40

**Comment by OkonSamuel** [comment]
@ablaom. The `nc>1` check ([here](https://github.com/JuliaAI/MLJMultivariateStatsInterface.jl/blob/dev/src/models/discriminant_analysis.jl#L84-L91)) is needed for `SubspaceLDA` and `BayesianSubspaceLDA` otherwise an empty LDA projection (see [here](https://github.com/JuliaAI/MLJMultivariateStatsInterface.jl/blob/dev/src/models/discriminant_analysis.jl#L351-L353))would be returned which would be useless for prediction purposes since it can't be indexed.  
To confirm this consider the code below
```julia
julia> using MultivariateStats

julia> X = rand(5, 5)
5×5 Matrix{Float64}:
 0.555036  0.139782   0.729986  0.482666  0.339284
 0.045016  0.912916   0.566781  0.110083  0.495788
 0.324991  0.951135   0.753715  0.103505  0.828286
 0.280403  0.0956383  0.81681   0.816009  0.729258
 0.481897  0.0691072  0.732923  0.466879  0.85996

julia> y = repeat([1], 5)
5-element Vector{Int64}:
 1
 1
 1
 1
 1

julia> MS = MultivariateStats.fit(SubspaceLDA, X, y)
SubspaceLDA{Float64}([-0.29327457564634163 0.1534893245245258 -0.2696064616419766 -0.9042894037076474; 0.5866129709626009 0.326541071371388 0.3829256117011211 -0.2502906497483902; … ; -0.4167183019348414 0.5496947477763965 0.6558223828359053 0.0336032691015139; -0.3134889660861893 0.5780745687681941 -0.4876749454831045 0.34415795865052956], Matrix{Float64}(undef, 4, 0), Float64[], [0.4493506606668266; 0.4261169426767129; … ; 0.5476237687453269; 0.5221533324801207;;], [5])

julia> projLDA = MS.projLDA
4×0 Matrix{Float64}
```

**Comment by OkonSamuel** [comment]
For the `LDA` and `BayesianLDA`, I now remember the reason I added the `nc > 1` check. Your right that the code works in when you removed the `nc > 1` check, but that only works for a `SimpleCovariance()` estimator. For more general estimators from [CovarianceEstimation.jl](https://github.com/mateuszbaran/CovarianceEstimation.jl), at least two classes are required. Even in the case of a `SimpleCovariannce` estimator it would fail for `SimpleCovariance(;corrected=true)`. To show this consider the julia code snippet below in which the `nc >1` check has been disabled.:
```julia
julia> using MLJ, MLJMultivariateStatsInterface
[ Info: Precompiling MLJMultivariateStatsInterface [1b6a4a23-ba22-4f51-9698-8599985d3728]

julia> X = MLJ.table(rand(5, 5))
Tables.MatrixTable{Matrix{Float64}} with 5 rows, 5 columns, and schema:
 :x1  Float64
 :x2  Float64
 :x3  Float64
 :x4  Float64
 :x5  Float64

julia> y = categorical(repeat([1], 5))
5-element CategoricalArrays.CategoricalArray{Int64,1,UInt32}:
 1
 1
 1
 1
 1

julia> mach = machine(LDA(cov_b=SimpleCovariance(;corrected=true)), X, y)
Machine trained 0 times; caches data
  model: LDA(method = gevd, …)
  args:
    1:  Source @008 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @605 ⏎ `AbstractVector{Multiclass{1}}`


julia> fit!(mach)
[ Info: Training machine(LDA(method = gevd, …), …).
┌ Error: Problem fitting the machine machine(LDA(method = gevd, …), …).
└ @ MLJBase C:\Users\OKON SAMUEL\.julia\packages\MLJBase\rQDaq\src\machines.jl:617
[ Info: Running type checks...
[ Info: Type checks okay.
ERROR: PosDefException: matrix is not positive definite; Cholesky factorization failed.
[...]

julia> mach = machine(LDA(cov_b=SimpleCovariance()), X, y)
Machine trained 0 times; caches data
  model: LDA(method = gevd, …)
  args:
    1:  Source @914 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @618 ⏎ `AbstractVector{Multiclass{1}}`
```
**EDIT:** There are two issues here
1. The resulting between-class covariance matrix is the null matrix (i.e rank 0)
2. When a correction factor `nc - 1` is applied by the between-class covariance estimator, there is a divison by zero which when combined with point (1) above leads to several `NaN` in the estimated between-class covariance matrix.

Point (1) doesn't really affect the predict/transform as in this case the model would predict a constant class, Point (2) is where the real issue is, but this too can be avoided by avoiding the division by the correction factor `nc - 1`. 
For now the only way we can avoid this from MLJ's end is to restrict the between-class covariance estimator to `SimpleCovariance()` for the case where the number of classes seen in the training sample is `1`.

**Comment by ablaom** [comment]
Thanks for the explanation. Still, we could be less restrictive: only throw an informative error if using an estimator different from the default  `SimpleCovariance()`, yes?

**Comment by OkonSamuel** [comment]
> Thanks for the explanation. Still, we could be less restrictive: only throw an informative error if using an estimator different from the default `SimpleCovariance()`, yes?

Yes, that's possible.
